// <auto-generated />
using System;
using GameSphere.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GameSphere.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GameSphere.Models.Post", b =>
                {
                    b.Property<int>("PostID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Message");

                    b.Property<int?>("userID");

                    b.HasKey("PostID");

                    b.HasIndex("userID");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("GameSphere.Models.User", b =>
                {
                    b.Property<int>("userID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Console");

                    b.Property<string>("Game");

                    b.Property<string>("Genre");

                    b.Property<string>("Platform");

                    b.Property<bool>("Privacy");

                    b.Property<string>("UserName");

                    b.HasKey("userID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GameSphere.Models.Post", b =>
                {
                    b.HasOne("GameSphere.Models.User", "User")
                        .WithMany("Posts")
                        .HasForeignKey("userID");
                });
#pragma warning restore 612, 618
        }
    }
}
